version: "3"
services:
  service-master:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: service-master
    ports:
      - "8002:8002"
    networks:
      - api-gateway_some-net
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.example

networks:
  api-gateway_some-net:
    external: true